// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"go-wire/model"
)

// Injectors from main.go:

func initMission(name string) model.Mission {
	player := model.NewPlayer(name)
	monster := model.NewMonster()
	mission := model.NewMission(player, monster)
	return mission
}

// main.go:

func main() {
	withOutInjection()
	initMission("Eminem").Start()
}

func withOutInjection() {
	monster := model.NewMonster()
	player := model.NewPlayer("Eminem")
	mission := model.NewMission(player, monster)

	mission.Start()
}
